package com.example.funquiz;

import android.content.Intent;
import android.graphics.RenderEffect;
import android.graphics.Shader;
import android.os.Build;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.fragment.app.Fragment;

public class SportFragment extends Fragment {

    public SportFragment() {
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_sport, container, false);

        String titleHistory = "Sejarah Olahraga";
        String titleExtra = "Aturan dan Tips";

        view.findViewById(R.id.card_golf).setOnClickListener(v -> openDetail(
                R.drawable.golf,
                "Golf",
                "Golf adalah olahraga presisi yang elegan dan menantang, dimainkan di lapangan hijau yang luas dengan berbagai rintangan alami maupun buatan. Tujuan utama seorang pegolf adalah memukul bola kecil berlesung pipit ke dalam serangkaian lubang, biasanya 9 atau 18, dengan menggunakan tongkat khusus yang disebut klab. Yang membuat golf unik adalah ia bukan hanya tentang kekuatan, tetapi juga tentang akurasi yang luar biasa, strategi cerdas dalam memilih klab dan arah pukulan, serta ketenangan mental yang diperlukan untuk mengatasi tekanan. Setiap lubang memiliki par-nya sendiri, yaitu jumlah pukulan yang diharapkan seorang pegolf ahli untuk menyelesaikannya, dan pegolf berusaha mencapai skor serendah mungkin.",
                "Sejarah golf modern dapat dilacak dengan sangat jelas ke Skotlandia pada abad ke-15. Bukti tertulis pertama tentang golf berasal dari tahun 1457, ketika Parlemen Skotlandia mengeluarkan larangan bermain 'gowf' karena dianggap mengganggu latihan panahan untuk persiapan perang. Namun, olahraga ini tetap populer di kalangan bangsawan Skotlandia, termasuk Raja James IV, yang kemudian mencabut larangan tersebut. Klub golf pertama dan aturan formal mulai distandarisasi di St Andrews, yang kini dikenal sebagai 'Home of Golf', dengan pembentukan The Royal and Ancient Golf Club of St Andrews pada tahun 1754. Dari Skotlandia, golf menyebar ke seluruh Britania Raya dan kemudian ke seluruh dunia melalui Kekaisaran Inggris. Turnamen besar seperti The Open Championship (pertama kali diadakan tahun 1860) membantu mempopulerkan golf secara global, menjadikannya olahraga yang kini dinikmati oleh jutaan orang dari berbagai kalangan.",
                "Lapangan golf umumnya memiliki 18 lubang, masing-masing dengan teeing ground (area awal), fairway (area rumput pendek), rough (rumput panjang), bunker (cekungan pasir), dan green (area rumput terpendek di sekitar lubang). Setiap pukulan dihitung sebagai satu stroke. Skor ditentukan oleh total jumlah stroke untuk menyelesaikan lapangan. **Aturan penting** meliputi tidak boleh menyentuh bola saat bermain (kecuali saat menempatkan di tee atau mengambil dari lubang), penalti untuk bola yang keluar batas (out of bounds) atau masuk ke rintangan air, serta etiket di lapangan seperti mengganti divot (gumpalan rumput yang terangkat) dan meratakan jejak kaki di bunker. **Tips untuk pegolf**: Fokus pada dasar-dasar teknik seperti grip yang benar, postur tubuh yang seimbang, dan ayunan yang halus. Latih pukulan chip dan putt Anda secara teratur, karena sebagian besar pukulan terjadi di sekitar green. Manajemen lapangan, yaitu strategi bermain setiap lubang, sangat krusial. Selain itu, kesabaran dan mentalitas yang kuat adalah kunci sukses dalam golf, karena ini adalah olahraga di mana Anda sering kali bersaing dengan diri sendiri dan tantangan lapangan.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_sepakbola).setOnClickListener(v -> openDetail(
                R.drawable.sepakbola,
                "Sepak Bola",
                "Sepak bola, yang secara universal dikenal sebagai 'the beautiful game' atau football, adalah olahraga tim yang paling populer dan paling banyak ditonton di dunia. Dimainkan oleh dua tim yang masing-masing beranggotakan sebelas pemain, tujuannya adalah mencetak gol dengan memasukkan bola ke gawang lawan menggunakan kaki atau bagian tubuh lainnya, kecuali tangan dan lengan (kecuali untuk penjaga gawang di area penaltinya). Olahraga ini bukan hanya tentang kekuatan fisik dan kecepatan, tetapi juga membutuhkan keterampilan teknis yang luar biasa dalam mengolah bola, visi strategis yang tajam untuk membaca permainan, dan kerja sama tim yang solid.",
                "Meskipun berbagai bentuk permainan menendang bola telah ada di berbagai budaya kuno (seperti Cuju di Tiongkok dan Harpastum di Romawi), sepak bola modern seperti yang kita kenal sekarang berakar kuat di sekolah-sekolah umum Inggris pada abad ke-19. Berbagai variasi aturan lokal menyebabkan kebingungan, sehingga pada tahun 1863, Football Association (FA) didirikan di London untuk menyatukan dan menstandarisasi aturan permainan. Ini adalah momen krusial yang membentuk dasar sepak bola modern. Sejak itu, olahraga ini menyebar dengan cepat ke seluruh dunia, terutama melalui pengaruh Kerajaan Inggris. Pendirian FIFA (Fédération Internationale de Football Association) pada tahun 1904 memicu pertumbuhan global yang eksplosif. Piala Dunia FIFA, yang pertama kali diselenggarakan pada tahun 1930 di Uruguay, telah tumbuh menjadi acara olahraga tunggal terbesar di dunia, menarik miliaran penggemar dan menjadi festival global empat tahunan yang merayakan persatuan melalui olahraga.",
                "Pertandingan sepak bola profesional dimainkan dalam dua babak berdurasi masing-masing 45 menit, dengan jeda 15 menit di antara babak. Setiap tim terdiri dari 10 pemain lapangan dan 1 penjaga gawang. **Aturan dasar** meliputi: **Offside**, di mana pemain berada di posisi offside jika dia lebih dekat ke garis gawang lawan daripada bola dan pemain lawan kedua terakhir saat bola dimainkan kepadanya. **Pelanggaran (Foul)** dapat menghasilkan tendangan bebas langsung atau tidak langsung, atau tendangan penalti jika terjadi di dalam area penalti. **Kartu kuning** diberikan untuk pelanggaran ringan, dan **kartu merah** untuk pelanggaran serius, yang mengakibatkan pengusiran pemain. **Hands-ball** adalah pelanggaran jika pemain lapangan menyentuh bola dengan tangan atau lengan secara sengaja. **Tips untuk pemain sepak bola**: Kuasai teknik dasar seperti **mengoper (passing)** dengan akurasi, **menggiring (dribbling)** bola dengan kontrol penuh, **menendang (shooting)** dengan kekuatan dan presisi, serta **mengontrol bola (first touch)** dengan baik. Peningkatan **kebugaran fisik** (daya tahan, kecepatan, kekuatan) sangat penting. **Visi permainan** dan **komunikasi** dengan rekan setim adalah kunci untuk mengembangkan taktik tim yang efektif dan memenangkan pertandingan.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_triathlon).setOnClickListener(v -> openDetail(
                R.drawable.thriathlon,
                "Triathlon",
                "Triathlon adalah olahraga multi-disiplin yang sangat menuntut, menguji batas ketahanan fisik dan mental seorang atlet melalui tiga segmen berbeda yang dilakukan secara berurutan dan tanpa henti: berenang, bersepeda, dan lari. Atlet harus beralih dari satu disiplin ke disiplin berikutnya dengan cepat di area transisi yang ditentukan. Ini bukan hanya tentang menyelesaikan setiap bagian, tetapi juga tentang mengelola energi, memahami pacing yang tepat, dan memiliki kemampuan transisi yang efisien untuk meminimalkan waktu istirahat dan memaksimalkan kinerja keseluruhan.",
                "Meskipun konsep mengombinasikan beberapa disiplin olahraga telah ada sejak lama, triathlon modern pertama kali muncul secara resmi pada tahun 1974 di San Diego, California, dengan 'Mission Bay Triathlon' yang diadakan oleh San Diego Track Club. Ide ini dengan cepat menyebar dan menarik perhatian para atlet. Namun, titik balik terbesar dalam sejarah triathlon datang pada tahun 1978 dengan lahirnya 'Ironman Triathlon' di Hawaii, sebuah tantangan ekstrem yang menggabungkan renang 2.4 mil (3.86 km), bersepeda 112 mil (180.25 km), dan maraton penuh 26.2 mil (42.2 km). Keberhasilan dan publisitas Ironman mendorong popularitas triathlon secara global. Puncaknya, triathlon diakui sebagai olahraga Olimpiade dan pertama kali dipertandingkan pada Olimpiade Sydney tahun 2000, mengukuhkan posisinya sebagai salah satu olahraga ketahanan paling prestisius di dunia.",
                "Triathlon terdiri dari tiga segmen utama: **Renang** (biasanya di perairan terbuka seperti laut atau danau), diikuti oleh **Bersepeda** (di jalan raya atau jalur khusus), dan diakhiri dengan **Lari** (di jalan raya atau lintasan). **Jarak lomba** bervariasi secara signifikan: dari **Sprint Triathlon** (misalnya, 750m renang, 20km sepeda, 5km lari), **Olympic/Standard Distance** (1.5km renang, 40km sepeda, 10km lari), hingga **Half Ironman** dan **Full Ironman** yang sangat ekstrem. **Aturan utama** meliputi penggunaan pakaian renang yang disetujui, kewajiban memakai helm saat bersepeda, dan kepatuhan terhadap rute yang telah ditentukan. Area transisi adalah zona vital di mana atlet harus berganti pakaian dan peralatan dengan cepat. **Tips untuk atlet triathlon**: Lakukan **latihan silang (cross-training)** untuk membangun kekuatan dan daya tahan di ketiga disiplin. Latih **transisi** secara berulang-ulang untuk meminimalkan waktu yang hilang. Perhatikan **nutrisi dan hidrasi** secara ketat, baik sebelum, selama, maupun setelah latihan dan lomba. Pelajari tentang **pacing** yang efektif untuk mengelola energi Anda sepanjang balapan yang panjang, dan jangan pernah memulai terlalu cepat. Persiapan mental sama pentingnya dengan persiapan fisik; ketahanan dan determinasi sangat diperlukan untuk melewati tantangan triathlon.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_basket).setOnClickListener(v -> openDetail(
                R.drawable.basket,
                "Basket",
                "Bola Basket adalah olahraga tim yang cepat, dinamis, dan sangat strategis, dimainkan oleh dua tim yang masing-masing beranggotakan lima pemain di lapangan berbentuk persegi panjang. Tujuan utama setiap tim adalah mencetak poin dengan melempar bola ke dalam keranjang lawan, yang terletak pada ketinggian 10 kaki (sekitar 3.05 meter) di atas lapangan. Selain mencetak gol, tim juga harus secara aktif bertahan untuk mencegah tim lawan mencetak angka. Olahraga ini menuntut kombinasi luar biasa dari kelincahan, kecepatan, koordinasi mata-tangan, kemampuan melompat yang eksplosif, dan pemikiran taktis yang cepat.",
                "Bola Basket memiliki sejarah yang sangat jelas dan unik, diciptakan pada Desember 1891 oleh Dr. James Naismith, seorang instruktur pendidikan jasmani Kanada di Springfield, Massachusetts, Amerika Serikat. Naismith ditugaskan untuk menciptakan olahraga baru yang tidak terlalu kasar dan aman untuk dimainkan di dalam ruangan selama musim dingin, sebagai alternatif dari sepak bola Amerika. Ia merancang 13 aturan dasar dan menggunakan keranjang buah persik sebagai keranjang pertama. Pertandingan bola basket pertama dimainkan pada 18 Desember 1891. Olahraga ini dengan cepat menyebar ke seluruh Amerika Serikat melalui YMCA (Young Men's Christian Association) dan kemudian ke seluruh dunia. Federasi Bola Basket Internasional (FIBA) didirikan pada tahun 1932. NBA (National Basketball Association) didirikan pada tahun 1946 dan telah berkembang menjadi liga bola basket profesional terkemuka di dunia. Bola basket menjadi olahraga Olimpiade penuh pada Olimpiade Berlin 1936.",
                "Sebuah pertandingan bola basket dibagi menjadi empat kuarter, dengan durasi bervariasi tergantung pada liga (misalnya, 12 menit di NBA, 10 menit di FIBA). **Aturan kunci** meliputi: **Dribbling** (memantulkan bola) harus dilakukan saat bergerak dengan bola. **Travelling** (berjalan lebih dari dua langkah tanpa mendribel) dan **Double Dribble** (mendribel bola, berhenti, lalu mendribel lagi) adalah pelanggaran. **Foul** adalah pelanggaran kontak fisik ilegal terhadap lawan; pemain yang melakukan foul berlebihan akan dikeluarkan dari permainan. **Poin** dicetak dari free throw (1 poin), field goal di dalam garis 3 poin (2 poin), atau field goal di luar garis 3 poin (3 poin). **Tips untuk pemain basket**: Kuasai **dribbling** dengan kedua tangan dan dalam berbagai kecepatan. Latih **shooting** dari berbagai posisi di lapangan, termasuk lay-up dan jump shot, dan biasakan diri dengan teknik **follow-through** yang benar. Kembangkan **passing** yang akurat dan tepat waktu, serta belajar melakukan **pivot** dengan baik. Di sisi pertahanan, fokus pada **posisi bertahan**, **block shot**, dan **rebound**. **Komunikasi** yang efektif dengan rekan tim, **pemahaman posisi** (point guard, shooting guard, small forward, power forward, center), dan kemampuan untuk **beradaptasi dengan strategi lawan** adalah kunci untuk menjadi pemain basket yang komplit dan sukses.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_tenismeja).setOnClickListener(v -> openDetail(
                R.drawable.tenismeja,
                "Tenis Meja",
                "Tenis Meja, yang juga populer dengan nama 'ping-pong', adalah olahraga raket yang sangat cepat dan mengandalkan refleks, dimainkan di atas meja yang dibagi dua oleh jaring kecil. Olahraga ini dapat dimainkan secara tunggal (dua pemain) atau ganda (dua pasang pemain). Menggunakan raket ringan (disebut bet) dan bola kecil yang sangat ringan, tujuannya adalah memukul bola melewati net sehingga lawan gagal mengembalikannya dengan benar atau bola memantul lebih dari sekali di sisi lawan. Kecepatan reaksi, koordinasi mata-tangan yang luar biasa, serta kemampuan strategis untuk menempatkan bola dan memvariasikan putaran adalah kunci sukses dalam tenis meja.",
                "Asal-usul Tenis Meja dapat ditelusuri kembali ke akhir abad ke-19 di Inggris, di mana ia dimulai sebagai permainan setelah makan malam di kalangan masyarakat kelas atas sebagai adaptasi 'miniatur' dari tenis lapangan. Para pemain awalnya menggunakan buku sebagai net, tutup kotak cerutu sebagai raket, dan bola gabus atau tali sebagai bola. Permainan ini dengan cepat populer di seluruh Inggris dan kemudian menyebar ke seluruh dunia. Nama 'ping-pong' berasal dari suara yang dihasilkan oleh pantulan bola. Asosiasi Tenis Meja didirikan di Inggris pada tahun 1921, dan Federasi Tenis Meja Internasional (ITTF) didirikan pada tahun 1926, yang menstandarisasi aturan. Tenis Meja membuat debutnya sebagai olahraga Olimpiade pada tahun 1988 di Seoul, Korea Selatan, dan sejak itu menjadi salah satu olahraga paling dominan di Asia, terutama di Tiongkok.",
                "Sebuah pertandingan tenis meja dimainkan dalam serangkaian game, biasanya best of 5 atau best of 7. Setiap game dimainkan hingga seorang pemain atau tim mencapai 11 poin, dengan syarat harus unggul minimal 2 poin dari lawan. Jika skor 10-10, permainan berlanjut hingga salah satu pihak unggul 2 poin. **Aturan dasar servis**: Bola harus dilambungkan minimal 16 cm (6,3 inci) ke atas sebelum dipukul. Bola harus memantul sekali di sisi server dan sekali di sisi lawan. Jika bola menyentuh net saat servis dan masih masuk ke area lawan, itu disebut 'let' dan servis diulang. **Tips untuk meningkatkan permainan Anda**: Latih berbagai jenis **servis** (topspin, backspin, sidespin) untuk mengejutkan lawan. Kuasai **forehand** dan **backhand drive** untuk pukulan ofensif, serta **push** dan **chop** untuk pukulan defensif. Tingkatkan **gerakan kaki** Anda agar selalu berada dalam posisi yang baik untuk memukul bola. Fokus pada **penempatan bola** daripada hanya kekuatan, dan pelajari cara **membaca putaran (spin)** pada bola lawan untuk mengembalikannya dengan efektif. Konsistensi, kesabaran, dan kemampuan untuk beradaptasi dengan gaya bermain lawan adalah aspek penting untuk menjadi pemain tenis meja yang tangguh.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_surfing).setOnClickListener(v -> openDetail(
                R.drawable.surfing,
                "Surfing",
                "Surfing adalah olahraga air yang memukau dan mengasyikkan, di mana peselancar menunggangi bagian depan atau wajah gelombang bergerak yang membawa mereka menuju pantai. Ini bukan hanya sekadar olahraga, melainkan sebuah gaya hidup yang erat kaitannya dengan laut, alam, dan pencarian ombak sempurna. Surfing membutuhkan kombinasi yang luar biasa antara keseimbangan, kekuatan inti, daya tahan, dan pemahaman mendalam tentang oseanografi — bagaimana ombak terbentuk, bergerak, dan pecah. Setiap ombak menawarkan tantangan dan pengalaman yang unik, menjadikan surfing aktivitas yang selalu dinamis dan tak pernah membosankan.",
                "Sejarah surfing sangatlah kuno, berakar jauh di dalam kebudayaan Polinesia kuno, khususnya di kepulauan Hawaii. Bagi masyarakat Hawaii kuno, surfing (atau 'he'e nalu' - meluncur ombak) adalah bagian integral dari kehidupan sehari-hari, sebuah aktivitas yang dipersembahkan kepada para dewa, dan indikator status sosial. Bangsawan Hawaii, atau 'Ali'i', adalah peselancar terhebat, menggunakan papan kayu panjang yang diukir tangan dan diwariskan dari generasi ke generasi. Olahraga ini pertama kali didokumentasikan oleh penjelajah Eropa Kapten James Cook pada tahun 1778. Namun, setelah kedatangan misionaris pada abad ke-19, surfing sempat mengalami kemunduran karena dianggap tidak bermoral. Kebangkitan surfing dimulai pada awal abad ke-20 berkat upaya Duke Kahanamoku, seorang perenang Olimpiade Hawaii yang mempopulerkan surfing di seluruh dunia. Sejak itu, surfing telah berkembang menjadi fenomena global, dengan budaya pantai yang ikonik dan kompetisi profesional yang menarik jutaan penggemar.",
                "Surfing tidak memiliki 'aturan' formal seperti olahraga tim, tetapi ada **etika di lineup** yang sangat penting untuk menjaga keselamatan dan kesenangan semua peselancar. **Prioritas ombak** diberikan kepada peselancar yang paling dekat dengan puncak ombak (peak) saat ombak mulai pecah. **'Dropping in'** (mencuri ombak peselancar lain yang sudah memiliki prioritas) dianggap pelanggaran etika serius. **Keselamatan** adalah yang utama: selalu periksa kondisi ombak, arus, dan bahaya bawah air sebelum masuk. Jangan berselancar sendirian di tempat yang tidak dikenal. **Tips untuk peselancar pemula**: Mulailah dengan **papan yang lebih besar dan stabil (funboard atau longboard)** untuk memudahkan keseimbangan dan menangkap ombak. Latih **'pop-up'** (gerakan cepat berdiri di papan) di pasir terlebih dahulu hingga sempurna. Pelajari cara **membaca ombak** – mengidentifikasi ombak yang bagus, kapan harus mendayung, dan di mana posisi terbaik untuk menangkapnya. **Kesabaran dan ketekunan** adalah kunci; belajar surfing membutuhkan waktu dan banyak usaha. Mulailah di ombak kecil dan secara bertahap tingkatkan ke ombak yang lebih besar seiring dengan peningkatan keterampilan Anda. Memahami **arus laut** dan **pasang surut** juga sangat penting untuk keamanan dan penentuan lokasi yang optimal.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_badminton).setOnClickListener(v -> openDetail(
                R.drawable.badminton,
                "Badminton",
                "Badminton, atau bulu tangkis, adalah olahraga raket yang intens, cepat, dan membutuhkan kelincahan luar biasa, dimainkan oleh dua pemain yang saling berhadapan (tunggal) atau dua pasangan yang saling berhadapan (ganda). Tujuan utamanya adalah memukul kok (shuttlecock) dengan raket melewati net sehingga mendarat di area lawan dan lawan tidak dapat mengembalikannya dengan benar sebelum kok menyentuh tanah. Olahraga ini menuntut kombinasi kekuatan pergelangan tangan, kecepatan reaksi, akurasi pukulan, dan strategi cerdas untuk mengecoh lawan.",
                "Badminton modern memiliki akar yang jelas dari permainan kuno yang dimainkan di India yang disebut 'Poona' atau 'Poonah', yang sangat populer di kalangan perwira militer Inggris yang bertugas di sana pada abad ke-19. Para perwira ini membawa permainan tersebut kembali ke Inggris. Nama 'Badminton' sendiri berasal dari Badminton House di Gloucestershire, Inggris, kediaman Duke of Beaufort, di mana permainan ini sering dimainkan pada tahun 1860-an. Aturan resmi pertama kali disusun pada tahun 1893 oleh Asosiasi Badminton Inggris. Federasi Badminton Internasional (IBF, sekarang BWF - Badminton World Federation) didirikan pada tahun 1934, membantu menyebarkan olahraga ini ke seluruh dunia. Badminton menjadi olahraga Olimpiade penuh pada Olimpiade Barcelona 1992, dan sejak itu, dominasi negara-negara Asia seperti Indonesia, Tiongkok, Malaysia, dan Korea Selatan semakin mengukuhkan posisinya sebagai kekuatan global dalam olahraga ini.",
                "Sebuah pertandingan badminton dimainkan dalam format best of 3 game. Setiap game dimainkan hingga seorang pemain atau pasangan mencapai 21 poin, dengan syarat harus unggul minimal 2 poin dari lawan. Jika skor 20-20, permainan berlanjut hingga ada keunggulan 2 poin atau hingga salah satu pihak mencapai 30 poin (disebut 'setting'). **Aturan dasar servis**: Server dan penerima servis harus berdiri secara diagonal di dalam kotak servis mereka. Kok harus dipukul di bawah pinggang server dan harus melewati net serta mendarat di area servis lawan yang benar. Kok yang menyentuh net saat servis dan masih masuk dianggap 'let' dan diulang. **Pelanggaran umum** meliputi kok yang mendarat di luar garis, kok menyentuh net dan tidak melewati, atau pemain menyentuh net dengan raket atau bagian tubuh. **Tips untuk meningkatkan permainan Anda**: Latih berbagai jenis **pukulan dasar** seperti **clear** (pukulan tinggi ke belakang lawan), **drop shot** (pukulan pendek yang jatuh dekat net), **smash** (pukulan cepat dan menukik), dan **drive** (pukulan datar cepat). Tingkatkan **gerakan kaki** Anda di lapangan agar Anda selalu siap memukul kok. Kembangkan **kontrol raket** dan **kekuatan pergelangan tangan** Anda untuk menghasilkan pukulan yang bertenaga dan akurat. **Antisipasi** dan **strategi penempatan kok** yang cerdas sangat penting untuk mengecoh lawan dan memenangkan poin dalam badminton.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_panjattebing).setOnClickListener(v -> openDetail(
                R.drawable.panjattebing,
                "Panjat Tebing",
                "Panjat Tebing adalah olahraga yang menggabungkan kekuatan fisik, ketahanan mental, kelenturan, dan pemecahan masalah dalam usaha untuk mendaki formasi batuan alami atau dinding buatan (sering disebut panjat dinding) hingga mencapai puncak atau titik akhir rute yang ditentukan. Olahraga ini bukan hanya tentang otot, tetapi juga tentang seni gerak, keseimbangan, dan kemampuan untuk 'membaca' rute—mengidentifikasi handholds dan footholds terbaik, serta merencanakan urutan gerakan yang paling efisien dan aman. Ini adalah olahraga yang menghadirkan tantangan fisik dan intelektual yang mendalam.",
                "Meskipun aktivitas mendaki gunung sudah ada sejak zaman prasejarah, panjat tebing sebagai olahraga terpisah mulai berkembang pada akhir abad ke-19 dan awal abad ke-20 di pegunungan Alpen Eropa. Awalnya, panjat tebing adalah bagian dari pendakian gunung yang lebih besar, tetapi seiring waktu, para pendaki mulai fokus pada rute yang lebih teknis dan sulit, memisahkan aspek 'panjat' dari 'mendaki gunung'. Peralatan seperti tali, karabiner, dan perangkat pengaman terus berkembang, membuat olahraga ini lebih aman dan dapat diakses. Panjat dinding buatan pertama kali muncul pada pertengahan abad ke-20, memungkinkan para pemanjat berlatih di dalam ruangan terlepas dari cuaca. Popularitas panjat tebing terus meroket, dan puncaknya adalah ketika panjat tebing membuat debut Olimpiadenya di Olimpiade Tokyo 2020 (yang ditunda hingga 2021 karena pandemi). Ini mengukuhkan panjat tebing sebagai olahraga global yang diakui secara luas.",
                "Panjat tebing terbagi dalam beberapa disiplin utama: **Lead Climbing** melibatkan memanjat rute tinggi dengan tali pengaman yang dipasang dari bawah, di mana pemanjat mengamankan tali ke 'quickdraws' yang terpasang di dinding. Tujuannya adalah mencapai titik tertinggi. **Bouldering** adalah memanjat rute yang lebih pendek, tetapi sangat sulit secara teknis, tanpa tali pengaman. Sebagai gantinya, matras tebal diletakkan di bawah untuk meredam jatuh. **Speed Climbing** adalah balapan head-to-head untuk mencapai puncak rute standar yang sama secepat mungkin. **Aturan umum** meliputi penggunaan peralatan keselamatan yang bersertifikat (harness, tali, helm, sepatu panjat khusus, kapur tangan). Penting untuk selalu memeriksa simpul dan peralatan pengaman Anda sebelum memanjat. **Tips untuk pemanjat**: Mulailah dengan **dasar-dasar kekuatan jari dan inti tubuh** melalui latihan spesifik. Pelajari **teknik dasar** seperti 'flagging' (menyeimbangkan tubuh dengan satu kaki ke samping), 'drop-knee' (memutar lutut ke dalam untuk mendapatkan jangkauan lebih), dan **footwork** yang presisi. Sebelum memanjat, **visualisasikan rute** dan rencanakan urutan gerakan Anda. Jangan hanya mengandalkan kekuatan otot; **gunakan kaki Anda** dan **keseimbangan** untuk menghemat energi. Aspek **mental** seperti fokus, keberanian, dan kemampuan untuk tetap tenang di bawah tekanan sangat penting dalam panjat tebing.",
                titleHistory,
                titleExtra
        ));

        view.findViewById(R.id.card_poloair).setOnClickListener(v -> openDetail(
                R.drawable.poloair,
                "Polo Air",
                "Polo Air adalah olahraga tim yang sangat intens, membutuhkan kekuatan fisik yang luar biasa, daya tahan kardiovaskular, dan keterampilan berenang yang superior. Dimainkan di kolam renang besar oleh dua tim yang masing-masing beranggotakan tujuh pemain (enam pemain lapangan dan satu penjaga gawang), tujuannya adalah mencetak gol dengan melempar bola ke gawang lawan. Sering digambarkan sebagai kombinasi renang, gulat, dan sepak bola, polo air menuntut kemampuan untuk mengoper dan menembak bola sambil terus-menerus mengapung atau menginjak air tanpa menyentuh dasar kolam, menjadikannya salah satu olahraga air paling menantang.",
                "Polo Air memiliki sejarah yang menarik, berawal di Inggris Raya dan Skotlandia pada akhir abad ke-19. Awalnya, permainan ini lebih mirip 'rugby air', dimainkan di sungai dan danau dengan aturan yang kurang terstruktur, bahkan terkadang melibatkan kekerasan fisik yang signifikan. Kemudian, aturan direvisi dan permainan pindah ke kolam renang, menjadi lebih terorganisir dan berfokus pada keterampilan bola. Polo air mendapatkan popularitas yang cepat dan menjadi salah satu olahraga tim tertua yang dipertandingkan di Olimpiade, pertama kali tampil di Olimpiade Paris tahun 1900. Sejak itu, polo air telah berkembang menjadi olahraga internasional yang dimainkan di seluruh dunia, dengan federasi seperti FINA (kini World Aquatics) yang mengelola kompetisi global dan mengembangkan olahraga ini.",
                "Sebuah pertandingan polo air dibagi menjadi empat kuarter, dengan durasi biasanya 8 menit waktu bermain murni per kuarter. Pemain lapangan tidak diizinkan menyentuh dasar kolam jika kedalamannya lebih dari 1,5 meter. Mereka harus menggunakan teknik **'eggbeater kick'** (tendangan kaki yang mirip kocokan telur) untuk menjaga diri tetap tinggi di atas air dan stabil. **Aturan penting** meliputi: Pemain tidak boleh memegang bola dengan kedua tangan (kecuali penjaga gawang). Mendorong lawan di bawah air atau menghalangi gerakan lawan secara ilegal adalah pelanggaran. Pemain dapat dikeluarkan sementara (exclusion foul) atau permanen (major foul) untuk pelanggaran serius. **Tips untuk pemain polo air**: Tingkatkan **kemampuan renang** Anda secara signifikan, terutama sprint dan daya tahan. Kuasai **'eggbeater kick'** untuk mobilitas dan stabilitas di air. Latih **passing** dan **menembak** bola dengan satu tangan, serta kembangkan **visi periferal** untuk membaca pergerakan bola, rekan tim, dan lawan. **Kekuatan inti** dan **kekuatan lengan** sangat penting untuk mengontrol bola dan berduel dengan lawan. **Komunikasi tim** yang efektif dan pemahaman tentang **strategi bertahan dan menyerang** adalah esensial untuk sukses dalam olahraga tim yang cepat dan fisik ini.",
                titleHistory,
                titleExtra
        ));

        return view;


    }

    private void openDetail(int imageRes, String title, String description, String history, String extra, String titleHistory, String titleExtra) {
        Intent intent = new Intent(getActivity(), DetailActivity.class);
        intent.putExtra("imageRes", imageRes);
        intent.putExtra("title", title);
        intent.putExtra("description", description);
        intent.putExtra("history", history);
        intent.putExtra("extra", extra);
        intent.putExtra("titleHistory", titleHistory);
        intent.putExtra("titleExtra", titleExtra);
        startActivity(intent);
    }
}